name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - windows-latest
          - macos-latest
    steps:
    - name: Checkout vparse
      uses: actions/checkout@v2

    - uses: jiro4989/setup-nim-action@v1.1.2
      with:
        nim-version: 'stable'

    - name: Build Python3 library for Ubuntu
      if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-16.04'}}
      run: |
        nimble install -d -y
        nimble build_pylib
        source /etc/os-release
        PLATFORM_INFO="${ID}-${VERSION_ID}-$(uname -i)"
        ARCHIVE_FILENAME="vparse-$(cat src/vparsepkg/private/VERSION)-pylib-${PLATFORM_INFO}"
        tar -czf "${ARCHIVE_FILENAME}.tar.gz" vparse.so README.md LICENSE CHANGELOG.md THIRD_PARTY_LICENSES.md
        md5sum "${ARCHIVE_FILENAME}.tar.gz" > ${ARCHIVE_FILENAME}.tar.gz.md5

    - name: Build Python3 library for macOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        nimble install -d -y
        nimble build_pylib
        ARCHIVE_FILENAME="vparse-$(cat src/vparsepkg/private/VERSION)-pylib-macos"
        tar -czf "${ARCHIVE_FILENAME}.tar.gz" vparse.so README.md LICENSE CHANGELOG.md THIRD_PARTY_LICENSES.md
        md5 "${ARCHIVE_FILENAME}.tar.gz" > ${ARCHIVE_FILENAME}.tar.gz.md5

    - name: Build Python3 library for Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        nimble install -d -y
        nimble build_pylib
        $ARCHIVE_FILENAME="vparse-$(cat src/vparsepkg/private/VERSION)-pylib-win_x86_64"
        7z a -tzip "${ARCHIVE_FILENAME}.zip" vparse.pyd README.md LICENSE CHANGELOG.md THIRD_PARTY_LICENSES.md
        [string]$MD5 = (get-filehash -Algorithm MD5 "${ARCHIVE_FILENAME}.zip").Hash
        echo $MD5 > "${ARCHIVE_FILENAME}.zip.md5"

    - name: Upload artifacts
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        files: |
          *.tar.gz
          *.tar.gz.md5
          *.zip
          *.zip.md5
